CREATE TABLE IF NOT EXISTS items(
    id serial PRIMARY KEY NOT NULL,
    name VARCHAR NOT NULL,
    price NUMERIC(21, 2) NOT NULL
);


CREATE TABLE IF NOT EXISTS person(
    id serial PRIMARY KEY NOT NULL,
    name VARCHAR NOT NULL
);
CREATE TABLE IF NOT EXISTS card(
    name VARCHAR PRIMARY KEY NOT NULL,
    path VARCHAR NOT NULL,
    color VARCHAR NOT NULL,  
    kind VARCHAR NOT NULL  
);
